### ISSUE TITLE
[Tooling] Keep dependencies up-to-date

### ISSUE THREAD

**Issue by chris48s** [codebuddies/backend#131]
Set up dependabot/rennovate/whatever to automate dependency upgrades.

**Comment by BethanyG** [comment]
Commenting to hold off the bot.  _There are not enough hours in the day, sadly._

**Comment by chris48s** [comment]
> There are not enough hours in the day

Do you mean to set something up, or review the updates?
Enabling dependabot is now a one-click action in GitHub:

![Screenshot at 2020-09-18 20-19-46](https://user-images.githubusercontent.com/6025893/93637613-c5d72c80-f9ed-11ea-83d2-6195ad4a8af5.png)

**Comment by BethanyG** [comment]
@chris48s  - I mean a little of both.  See Issue https://github.com/codebuddies/backend/issues/182, for one piece - but that issue is already out of date, since I've had to rip out `drf-jwt` and implement `django-simpieJWT` instead because it is the only library that `dj-rest-auth` supports at the moment.  

So it sorta feels like turning on dependabot is the least (or at least the most straightforward) of our worries - we've got to get everything lined up at a starting point first -- or am I missing something?  Can we flip the switch on this and have it not interfere with the other things we need to upgrade/rework?

My current "plan" of attack is to get the registration options hooked up and tested, followed by any test-re-writing that the JWT and routing changes has caused.  I think then we can consider the stuff in #182...and then we implement dependabot?  what are your thoughts?

**Comment by chris48s** [comment]
Yeah while you haven't got anything deployed in front of real users, I suppose it makes relatively little difference at this stage if reviewing the bump PRs is going to detract from getting to a stage where you can _actually ship something_ :)

Re: django versions:
With django sites I tend to track LTS versions only, so I will upgrade to patch releases on 2.2.x and then jump from 2.2.x to 3.2.x but I won't bother tracking the intermediate 3.x releases. In general, the wider `django-` package ecosystem will be up to speed with the breaking 3.x changes by the time 3.2 is out and there will always be overlap between LTS releases (i.e: the 2.2.x branch will continue receiving patch releases for a while after 3.2 is out). Upgrading to every intermediate feature release carries an additional risk of ending up stuck on a deprecated release due to a transitive dependency esp if you carry a large dependency tree :deciduous_tree:  as the intermediate releases don't stay supported for long.

More info on django release schedules:
https://www.djangoproject.com/download/#supported-versions
![release-roadmap 3c7ece4f31b3](https://user-images.githubusercontent.com/6025893/93643504-05a31180-f9f8-11ea-8b62-cd16b770250e.png)
